from utils.llm import generate_quiz as _generate_quiz
from utils.memory import save_quiz_attempt, get_recent_quiz_questions


def create_quiz(user_id, subject, topic, num_questions=5, context=None):
    previous_questions = get_recent_quiz_questions(user_id, subject, topic)
    return _generate_quiz(subject, topic, num_questions, context, previous_questions)


def score_quiz(user_id, subject, topic, questions, user_answers):
    """
    questions: the list generated by create_quiz (each has correct_index)
    user_answers: list of selected option indices, same order/length
    """
    total = len(questions)
    score = 0
    review = []

    for i, q in enumerate(questions):
        selected = user_answers[i] if i < len(user_answers) else None
        correct = selected == q["correct_index"]
        if correct:
            score += 1
        review.append({
            "question": q["question"],
            "options": q["options"],
            "correct_index": q["correct_index"],
            "selected_index": selected,
            "is_correct": correct,
            "explanation": q.get("explanation", ""),
        })

    save_quiz_attempt(user_id, subject, topic, score, total, review)
    return {"score": score, "total": total, "review": review}